services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .config/.env
      - .config/postgres.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - reblend-network
    restart: unless-stopped

  db:
    image: postgres:18.1-alpine3.23
    ports:
      - "5432:5432"
    env_file:
      - .config/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U reblend -d reblend" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - reblend-network

networks:
  reblend-network:
    driver: bridge

volumes:
  postgres_data:
